[build]
  command = "ng build --configuration production"
  publish = "dist/VaultDay/browser"

[build.environment]
  NODE_VERSION = "20"

# SPA fallback (Angular router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
